# Generated by Django 6.1 on 2026-08-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=12)),
                ('FirstName', models.CharField(max_length=12)),
                ('LastName', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=12)),
            ],
        ),
    ]
