# Generated by Django 6.1.1 on 2026-09-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankstatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
