# Generated by Django 6.1.1 on 2026-09-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0003_bankstatement_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocksheld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stockname', models.CharField()),
                ('Amountheld', models.DecimalField(decimal_places=6, max_digits=10)),
                ('Averagecost', models.DecimalField(decimal_places=6, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Stockheld',
        ),
    ]
