# Generated by Django 6.1.1 on 2026-09-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0004_stocksheld_delete_stockheld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksheld',
            name='Averagecost',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
